# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-30 12:18
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='texts/')),
                ('md5_checksum', models.CharField(editable=False, max_length=16, unique=True)),
                ('stats', django.contrib.postgres.fields.jsonb.JSONField()),
                ('html_text', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
