# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-30 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indices', '0002_auto_20171230_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='md5_checksum',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
